#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Validating commit message..."
if ! pnpm commitlint --edit "$1"; then
  echo "❌ Commit message validation failed! Please follow the conventional commit format."
  exit 1
fi
echo "✅ Commit message is valid."
