#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

if ! git log -1 --pretty=format:'%h %G?' | grep -q 'G'; then
  echo "❌ ERROR: Your last commit is NOT signed!"
  exit 1
fi

echo "✅ Your last commit is signed. Pushing..."

